use_frameworks!

target 'LGWatermarkCamera_Example' do
  pod 'LGWatermarkCamera', :path => '../'

  target 'LGWatermarkCamera_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
